# Lychee link checker configuration
# https://github.com/lycheeverse/lychee

# Maximum number of concurrent requests
max_concurrency = 10

# Request timeout in seconds
timeout = 30

# User agent string
user_agent = "Mozilla/5.0 (X11; Linux x86_64; rv:27.0) Gecko/20100101 Firefox/27.0"

# Accept invalid certificates and insecure connections
insecure = false
accept = [200, 201, 204, 206, 301, 302, 303, 307, 308, 999]

# Exclude URLs matching these patterns
# Note: Specific problematic URLs are listed in .lycheeignore
exclude = [
    # Container registries (not browsable)
    "ghcr.io",
    "azurecr.io",
    "amazonaws.com",
    
    # Example domains
    "example.com",
    "example.org",
    "test.com",
    
    # Potentially unreliable external services
    "twitter.com",
    "x.com",
    "facebook.com",
    "linkedin.com",
    "instagram.com",
    "raw.githubusercontent.com",
    "hub.docker.com",
    "pypi.org",
]

# Include only these schemes
include = ["https", "http"]

# Check external links
include_verbatim = false

# Maximum number of redirects to follow
max_redirects = 5

# Retry configuration
retry_wait_time = 2
max_retries = 3 